### ISSUE TITLE
Scanner fails to scan sslv2.mozqa.com

### ISSUE THREAD

**Issue by marumari** [mozilla/tls-observatory#107]
```
 ❯ tlsobs -r sslv2.mozqa.com                                                                                 [17:50:47]
Scanning sslv2.mozqa.com (id 11713152)
Retrieving cached results from 1.155620276s ago. To run a new scan, use '-r'.


--- Ciphers Evaluation ---
prio cipher protocols pfs  curves
panic: runtime error: index out of range

goroutine 1 [running]:
main.printConnection(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/april/.go/src/github.com/mozilla/tls-observatory/tlsobs/main.go:178 +0x9ab
main.main()
	/Users/april/.go/src/github.com/mozilla/tls-observatory/tlsobs/main.go:113 +0xf16

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.5.3/libexec/src/runtime/asm_amd64.s:1721 +0x1

goroutine 19 [IO wait]:
net.runtime_pollWait(0x69e510, 0x72, 0xc8200121d0)
	/usr/local/Cellar/go/1.5.3/libexec/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820018290, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820018290, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820018230, 0xc820466000, 0x4000, 0x4000, 0x0, 0x699050, 0xc8200121d0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8200da000, 0xc820466000, 0x4000, 0x4000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc8200d80c0, 0x1360078, 0xc8200da000, 0x5, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/crypto/tls/conn.go:455 +0xcc
crypto/tls.(*Conn).readRecord(0xc8200e0000, 0x468d17, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/crypto/tls/conn.go:540 +0x2d1
crypto/tls.(*Conn).Read(0xc8200e0000, 0xc82017e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/crypto/tls/conn.go:901 +0x167
net/http.noteEOFReader.Read(0x136ca48, 0xc8200e0000, 0xc82000e108, 0xc82017e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc82044a6c0, 0xc82017e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	<autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc820375e00)
	/usr/local/Cellar/go/1.5.3/libexec/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc820375e00, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc82000e0b0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:685 +0xc78

goroutine 20 [select]:
net/http.(*persistConn).writeLoop(0xc82000e0b0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:686 +0xc9d

goroutine 50 [IO wait]:
net.runtime_pollWait(0x69e450, 0x72, 0xc8200121d0)
	/usr/local/Cellar/go/1.5.3/libexec/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8200184c0, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8200184c0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820018460, 0xc82009ac00, 0x400, 0x400, 0x0, 0x699050, 0xc8200121d0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc820032068, 0xc82009ac00, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc82000b770, 0x1360078, 0xc820032068, 0x5, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/crypto/tls/conn.go:455 +0xcc
crypto/tls.(*Conn).readRecord(0xc82000d080, 0x468d17, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/crypto/tls/conn.go:540 +0x2d1
crypto/tls.(*Conn).Read(0xc82000d080, 0xc8200eb000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/crypto/tls/conn.go:901 +0x167
net/http.noteEOFReader.Read(0x136ca48, 0xc82000d080, 0xc82000e268, 0xc8200eb000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc82043f1a0, 0xc8200eb000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	<autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc8205d3380)
	/usr/local/Cellar/go/1.5.3/libexec/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc8205d3380, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc82000e210)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:685 +0xc78

goroutine 51 [select]:
net/http.(*persistConn).writeLoop(0xc82000e210)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:686 +0xc9d
```

**Comment by floatingatoll** [comment]
I can provide any information necessary from our server configs for this one, if that's of any help.

**Comment by floatingatoll** [comment]
But I suspect this is the key bit:

```
ssl_support_ssl2	enabled
ssl_support_ssl3	disabled
ssl_support_tls1	disabled
ssl_support_tls1_1	disabled
ssl_support_tls1_2	disabled
```

**Comment by jvehent** [comment]
I think the issue comes from the certificate retriever, which uses golang's tls stack and does not support sslv3 and sslv2.

**Comment by floatingatoll** [comment]
You can also compare to ssl-md5.mozqa.com, which *supports* SSLv2 but may permit modern TLS versions, albeit with an MD5 cert instead of a SHA one.

**Comment by jvehent** [comment]
`ssl-md5.mozqa.com` works as expected.

**Comment by jvehent** [comment]
I genuinely wonder how much we want to care about this. Targets that only support sslv3 or believe are very rare. It may not be worth rewriting a certificate retriever with openssl just for those, but maybe it is...

**Comment by floatingatoll** [comment]
If the observatory mandates that a certificate must be available for the scan results to show it as an SSLv2 endpoint, then skip it. Otherwise, I would suggest logging "endpoint is SSLv2, certificate not downloaded" and moving on.

**Comment by jvehent** [comment]
We could catch the cert retrieval error and display a "certificate could not be retrieved" message back to the using, then proceed to display the ciphersuites.

**Comment by marumari** [comment]
Yeah, I'm okay with it not working, just as long as not working doesn't involve a two page long stack trace.

**Comment by jvehent** [comment]
Agreed, I'll make a patch for it.

**Comment by jvehent** [comment]
patch merged in https://github.com/mozilla/tls-observatory/commit/08fc009cd747be17b664955f4812990bd2058fa1
