### ISSUE TITLE
fatal error: runtime: out of memory

### ISSUE THREAD

**Issue by jammasterj89** [mozilla/tls-observatory#377]
Hi,

When going into the container via ` docker run -ti mozilla/tls-observatory:latest bash` and trying to `make` within `/go/src/github.com/mozilla/tls-observatory` I get the error below, any idea where I'm going wrong? Thanks!

<pre>fatal: Not a git repository (or any of the parent directories): .git
GOOS=linux GOARCH=amd64 go test `go list ./... | grep -v tools`
ok      github.com/mozilla/tls-observatory/certificate  0.585s
?       github.com/mozilla/tls-observatory/certificate/constraints      [no test files]
?       github.com/mozilla/tls-observatory/config       [no test files]
?       github.com/mozilla/tls-observatory/connection   [no test files]
?       github.com/mozilla/tls-observatory/constants    [no test files]
?       github.com/mozilla/tls-observatory/database     [no test files]
?       github.com/mozilla/tls-observatory/logger       [no test files]
?       github.com/mozilla/tls-observatory/metrics      [no test files]
?       github.com/mozilla/tls-observatory/tlsobs       [no test files]
# github.com/mozilla/tls-observatory/tlsobs-api.test
fatal error: runtime: out of memory
runtime stack:
runtime.throw(0x6731d0, 0x16)
        /tmp/go/src/runtime/panic.go:608 +0x72
runtime.sysMap(0xc008000000, 0x4000000, 0x847798)
        /tmp/go/src/runtime/mem_linux.go:165 +0xc7
runtime.(*mheap).sysAlloc(0x82fce0, 0x2000, 0x7f601ffa1ab0, 0x82fce0)
        /tmp/go/src/runtime/malloc.go:633 +0x1cb
runtime.(*mheap).grow(0x82fce0, 0x1, 0x0)
        /tmp/go/src/runtime/mheap.go:1094 +0x42
runtime.(*mheap).allocSpanLocked(0x82fce0, 0x1, 0x8477a8, 0x7f601ffa1ab0)
        /tmp/go/src/runtime/mheap.go:1018 +0x39e
runtime.(*mheap).alloc_m(0x82fce0, 0x1, 0xc000010011, 0x7f601ffa1ab0)
        /tmp/go/src/runtime/mheap.go:860 +0xc2
runtime.(*mheap).alloc.func1()
        /tmp/go/src/runtime/mheap.go:931 +0x4c
runtime.systemstack(0x0)
        /tmp/go/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
        /tmp/go/src/runtime/proc.go:1153

goroutine 1 [running]:
runtime.systemstack_switch()
        /tmp/go/src/runtime/asm_amd64.s:311 fp=0xc0006f05e0 sp=0xc0006f05d8 pc=0x454580
runtime.(*mheap).alloc(0x82fce0, 0x1, 0x20300200010011, 0x100)
        /tmp/go/src/runtime/mheap.go:930 +0x8a fp=0xc0006f0630 sp=0xc0006f05e0 pc=0x42325a
runtime.(*mcentral).grow(0x8304a0, 0x0)
        /tmp/go/src/runtime/mcentral.go:256 +0x93 fp=0xc0006f0678 sp=0xc0006f0630 pc=0x416483
runtime.(*mcentral).cacheSpan(0x8304a0, 0xc007ffbd60)
        /tmp/go/src/runtime/mcentral.go:106 +0x2ee fp=0xc0006f06d8 sp=0xc0006f0678 pc=0x415f9e
runtime.(*mcache).refill(0x7f6022615000, 0x11)
        /tmp/go/src/runtime/mcache.go:135 +0x86 fp=0xc0006f06f8 sp=0xc0006f06d8 pc=0x415a46
runtime.(*mcache).nextFree(0x7f6022615000, 0x807011, 0x3, 0x3, 0xffffffffffffffff)
        /tmp/go/src/runtime/malloc.go:786 +0x88 fp=0xc0006f0730 sp=0xc0006f06f8 pc=0x40b048
runtime.mallocgc(0x70, 0x61e1a0, 0xffffffffffffff01, 0x1)
        /tmp/go/src/runtime/malloc.go:939 +0x760 fp=0xc0006f07d0 sp=0xc0006f0730 pc=0x40b950
runtime.makeslice(0x61e1a0, 0x6e, 0x6e, 0x807006)
        /tmp/go/src/runtime/slice.go:49 +0x6c fp=0xc0006f0800 sp=0xc0006f07d0 pc=0x44012c
bytes.Replace(0xc007f59a52, 0x21, 0x71, 0x807006, 0x3, 0x3, 0xc007ffbdb0, 0x50, 0x50, 0x1, ...)
        /tmp/go/src/bytes/bytes.go:775 +0x92 fp=0xc0006f0888 sp=0xc0006f0800 pc=0x4bdc12
cmd/link/internal/objfile.(*objReader).patchDWARFName(0xc0006f0d68, 0xc007ede5b0)
        /tmp/go/src/cmd/link/internal/objfile/objfile.go:359 +0x20b fp=0xc0006f0970 sp=0xc0006f0888 pc=0x52830b
cmd/link/internal/objfile.(*objReader).readSym(0xc0006f0d68)
        /tmp/go/src/cmd/link/internal/objfile/objfile.go:340 +0xff4 fp=0xc0006f0b50 sp=0xc0006f0970 pc=0x527454
cmd/link/internal/objfile.(*objReader).loadObjFile(0xc0006f0d68)
        /tmp/go/src/cmd/link/internal/objfile/objfile.go:128 +0x376 fp=0xc0006f0cc0 sp=0xc0006f0b50 pc=0x525cc6
cmd/link/internal/objfile.Load(0x81bd20, 0xc0000680f0, 0xc0039ddb80, 0xc00153a410, 0x6aff5, 0xc007eae210, 0x2b)
        /tmp/go/src/cmd/link/internal/objfile/objfile.go:70 +0x1c4 fp=0xc0006f0e90 sp=0xc0006f0cc0 pc=0x525784
cmd/link/internal/ld.ldobj(0xc00068a000, 0xc0039ddb80, 0xc00153a410, 0x6b084, 0xc007eae210, 0x2b, 0xc0006995fb, 0x23, 0x0)
        /tmp/go/src/cmd/link/internal/ld/lib.go:1653 +0xc1f fp=0xc0006f1030 sp=0xc0006f0e90 pc=0x58595f
cmd/link/internal/ld.loadobjfile(0xc00068a000, 0xc00153a410)
        /tmp/go/src/cmd/link/internal/ld/lib.go:883 +0x445 fp=0xc0006f11c8 sp=0xc0006f1030 pc=0x57e935
cmd/link/internal/ld.(*Link).loadlib(0xc00068a000)
        /tmp/go/src/cmd/link/internal/ld/lib.go:381 +0x160 fp=0xc0006f13a0 sp=0xc0006f11c8 pc=0x57b350
cmd/link/internal/ld.Main(0x81bd20, 0x10, 0x20, 0x1, 0x7, 0x10, 0x67500e, 0x1b, 0x671bce, 0x14, ...)
        /tmp/go/src/cmd/link/internal/ld/main.go:207 +0xb3a fp=0xc0006f1510 sp=0xc0006f13a0 pc=0x595dba
main.main()
        /tmp/go/src/cmd/link/main.go:65 +0x1cf fp=0xc0006f1f98 sp=0xc0006f1510 pc=0x5f88cf
runtime.main()
        /tmp/go/src/runtime/proc.go:200 +0x207 fp=0xc0006f1fe0 sp=0xc0006f1f98 pc=0x42c537
runtime.goexit()
        /tmp/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc0006f1fe8 sp=0xc0006f1fe0 pc=0x4564d1
FAIL    github.com/mozilla/tls-observatory/tlsobs-api [build failed]
# github.com/mozilla/tls-observatory/tlsobs-runner.test
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x6731d0, 0x16)
        /tmp/go/src/runtime/panic.go:608 +0x72
runtime.sysMap(0xc008000000, 0x4000000, 0x847798)
        /tmp/go/src/runtime/mem_linux.go:165 +0xc7
runtime.(*mheap).sysAlloc(0x82fce0, 0x2c000, 0x7f92dcdc1cc8, 0x82fce0)
        /tmp/go/src/runtime/malloc.go:633 +0x1cb
runtime.(*mheap).grow(0x82fce0, 0x16, 0x0)
        /tmp/go/src/runtime/mheap.go:1094 +0x42
runtime.(*mheap).allocSpanLocked(0x82fce0, 0x16, 0x8477a8, 0x7ffe181cfda0)
        /tmp/go/src/runtime/mheap.go:1018 +0x39e
runtime.(*mheap).alloc_m(0x82fce0, 0x16, 0x7f92dcdc0100, 0x7ffe181cfde8)
        /tmp/go/src/runtime/mheap.go:860 +0xc2
runtime.(*mheap).alloc.func1()
        /tmp/go/src/runtime/mheap.go:931 +0x4c
runtime.(*mheap).alloc(0x82fce0, 0x16, 0x7f92dc010100, 0x7f92dcdc2658)
        /tmp/go/src/runtime/mheap.go:930 +0x8a
runtime.largeAlloc(0x2af80, 0x620001, 0x7f92dcdc2658)
        /tmp/go/src/runtime/malloc.go:1055 +0x97
runtime.mallocgc.func1()
        /tmp/go/src/runtime/malloc.go:950 +0x46
runtime.systemstack(0x454489)
        /tmp/go/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
        /tmp/go/src/runtime/proc.go:1153

goroutine 1 [running]:
runtime.systemstack_switch()
        /tmp/go/src/runtime/asm_amd64.s:311 fp=0xc0006f8958 sp=0xc0006f8950 pc=0x454580
runtime.mallocgc(0x2af80, 0x661f80, 0x1, 0xc0055c5d80)
        /tmp/go/src/runtime/malloc.go:949 +0x863 fp=0xc0006f89f8 sp=0xc0006f8958 pc=0x40ba53
runtime.makeslice(0x661f80, 0x3e8, 0x3e8, 0x5d)
        /tmp/go/src/runtime/slice.go:49 +0x6c fp=0xc0006f8a28 sp=0xc0006f89f8 pc=0x44012c
cmd/link/internal/sym.(*Symbols).Newsym(...)
        /tmp/go/src/cmd/link/internal/sym/symbols.go:57
cmd/link/internal/sym.(*Symbols).Lookup(0xc0000680f0, 0xc007fdb320, 0x5d, 0x0, 0xc007fbced0)
        /tmp/go/src/cmd/link/internal/sym/symbols.go:78 +0x24a fp=0xc0006f8a88 sp=0xc0006f8a28 pc=0x4eae6a
cmd/link/internal/objfile.(*objReader).readRef(0xc0006f8d68)
        /tmp/go/src/cmd/link/internal/objfile/objfile.go:394 +0xfd fp=0xc0006f8b50 sp=0xc0006f8a88 pc=0x52872d
cmd/link/internal/objfile.(*objReader).loadObjFile(0xc0006f8d68)
        /tmp/go/src/cmd/link/internal/objfile/objfile.go:110 +0x2c2 fp=0xc0006f8cc0 sp=0xc0006f8b50 pc=0x525c12
cmd/link/internal/objfile.Load(0x81bd20, 0xc0000680f0, 0xc0024405d0, 0xc002676a90, 0x79bba, 0xc007e11da0, 0x2b)
        /tmp/go/src/cmd/link/internal/objfile/objfile.go:70 +0x1c4 fp=0xc0006f8e90 sp=0xc0006f8cc0 pc=0x525784
cmd/link/internal/ld.ldobj(0xc000692000, 0xc0024405d0, 0xc002676a90, 0x79c49, 0xc007e11da0, 0x2b, 0xc0006a165d, 0x23, 0x0)
        /tmp/go/src/cmd/link/internal/ld/lib.go:1653 +0xc1f fp=0xc0006f9030 sp=0xc0006f8e90 pc=0x58595f
cmd/link/internal/ld.loadobjfile(0xc000692000, 0xc002676a90)
        /tmp/go/src/cmd/link/internal/ld/lib.go:883 +0x445 fp=0xc0006f91c8 sp=0xc0006f9030 pc=0x57e935
cmd/link/internal/ld.(*Link).loadlib(0xc000692000)
        /tmp/go/src/cmd/link/internal/ld/lib.go:381 +0x160 fp=0xc0006f93a0 sp=0xc0006f91c8 pc=0x57b350
cmd/link/internal/ld.Main(0x81bd20, 0x10, 0x20, 0x1, 0x7, 0x10, 0x67500e, 0x1b, 0x671bce, 0x14, ...)
        /tmp/go/src/cmd/link/internal/ld/main.go:207 +0xb3a fp=0xc0006f9510 sp=0xc0006f93a0 pc=0x595dba
main.main()
        /tmp/go/src/cmd/link/main.go:65 +0x1cf fp=0xc0006f9f98 sp=0xc0006f9510 pc=0x5f88cf
runtime.main()
        /tmp/go/src/runtime/proc.go:200 +0x207 fp=0xc0006f9fe0 sp=0xc0006f9f98 pc=0x42c537
runtime.goexit()
        /tmp/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc0006f9fe8 sp=0xc0006f9fe0 pc=0x4564d1
FAIL    github.com/mozilla/tls-observatory/tlsobs-runner [build failed]
?       github.com/mozilla/tls-observatory/tlsobs-scanner       [no test files]
?       github.com/mozilla/tls-observatory/worker       [no test files]
?       github.com/mozilla/tls-observatory/worker/awsCertlint   [no test files]
?       github.com/mozilla/tls-observatory/worker/caaWorker     [no test files]
?       github.com/mozilla/tls-observatory/worker/crlWorker     [no test files]
?       github.com/mozilla/tls-observatory/worker/evCheckerWorker       [no test files]
# github.com/mozilla/tls-observatory/worker/mozillaEvaluationWorker.test
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x6731d0, 0x16)
        /tmp/go/src/runtime/panic.go:608 +0x72
runtime.sysMap(0xc008000000, 0x4000000, 0x847798)
        /tmp/go/src/runtime/mem_linux.go:165 +0xc7
runtime.(*mheap).sysAlloc(0x82fce0, 0x14000, 0x7fb13dbfb138, 0x82fce0)
        /tmp/go/src/runtime/malloc.go:633 +0x1cb
runtime.(*mheap).grow(0x82fce0, 0xa, 0x0)
        /tmp/go/src/runtime/mheap.go:1094 +0x42
runtime.(*mheap).allocSpanLocked(0x82fce0, 0xa, 0x8477a8, 0x20300100000000)
        /tmp/go/src/runtime/mheap.go:1018 +0x39e
runtime.(*mheap).alloc_m(0x82fce0, 0xa, 0x100, 0x7fb13de29fff)
        /tmp/go/src/runtime/mheap.go:860 +0xc2
runtime.(*mheap).alloc.func1()
        /tmp/go/src/runtime/mheap.go:931 +0x4c
runtime.(*mheap).alloc(0x82fce0, 0xa, 0x7fb13d010100, 0x7fb13dbfb0a8)
        /tmp/go/src/runtime/mheap.go:930 +0x8a
runtime.largeAlloc(0x14000, 0x1, 0x7fb13dbfb0a8)
        /tmp/go/src/runtime/malloc.go:1055 +0x97
runtime.mallocgc.func1()
        /tmp/go/src/runtime/malloc.go:950 +0x46
runtime.systemstack(0x0)
        /tmp/go/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
        /tmp/go/src/runtime/proc.go:1153

goroutine 1 [running]:
runtime.systemstack_switch()
        /tmp/go/src/runtime/asm_amd64.s:311 fp=0xc000709068 sp=0xc000709060 pc=0x454580
runtime.mallocgc(0x14000, 0x64a180, 0xc001, 0xb70000c007fea000)
        /tmp/go/src/runtime/malloc.go:949 +0x863 fp=0xc000709108 sp=0xc000709068 pc=0x40ba53
runtime.growslice(0x64a180, 0xc007fea000, 0x555, 0x555, 0x556, 0xc007fea000, 0x400, 0x555)
        /tmp/go/src/runtime/slice.go:181 +0x1e4 fp=0xc000709170 sp=0xc000709108 pc=0x4403a4
cmd/link/internal/ld.deadcode(0xc000692000)
        /tmp/go/src/cmd/link/internal/ld/deadcode.go:92 +0x923 fp=0xc0007093a0 sp=0xc000709170 pc=0x555543
cmd/link/internal/ld.Main(0x81bd20, 0x10, 0x20, 0x1, 0x7, 0x10, 0x67500e, 0x1b, 0x671bce, 0x14, ...)
        /tmp/go/src/cmd/link/internal/ld/main.go:210 +0xb5c fp=0xc000709510 sp=0xc0007093a0 pc=0x595ddc
main.main()
        /tmp/go/src/cmd/link/main.go:65 +0x1cf fp=0xc000709f98 sp=0xc000709510 pc=0x5f88cf
runtime.main()
        /tmp/go/src/runtime/proc.go:200 +0x207 fp=0xc000709fe0 sp=0xc000709f98 pc=0x42c537
runtime.goexit()
        /tmp/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000709fe8 sp=0xc000709fe0 pc=0x4564d1
FAIL    github.com/mozilla/tls-observatory/worker/mozillaEvaluationWorker [build failed]
# github.com/mozilla/tls-observatory/worker/mozillaGradingWorker.test
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x6731d0, 0x16)
        /tmp/go/src/runtime/panic.go:608 +0x72
runtime.sysMap(0xc008000000, 0x4000000, 0x847798)
        /tmp/go/src/runtime/mem_linux.go:165 +0xc7
runtime.(*mheap).sysAlloc(0x82fce0, 0x2000, 0x7f0de8592520, 0x82fce0)
        /tmp/go/src/runtime/malloc.go:633 +0x1cb
runtime.(*mheap).grow(0x82fce0, 0x1, 0x0)
        /tmp/go/src/runtime/mheap.go:1094 +0x42
runtime.(*mheap).allocSpanLocked(0x82fce0, 0x1, 0x8477a8, 0x7f0de8592520)
        /tmp/go/src/runtime/mheap.go:1018 +0x39e
runtime.(*mheap).alloc_m(0x82fce0, 0x1, 0xc000010029, 0x7f0de8592520)
        /tmp/go/src/runtime/mheap.go:860 +0xc2
runtime.(*mheap).alloc.func1()
        /tmp/go/src/runtime/mheap.go:931 +0x4c
runtime.systemstack(0x0)
        /tmp/go/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
        /tmp/go/src/runtime/proc.go:1153

goroutine 1 [running]:
runtime.systemstack_switch()
        /tmp/go/src/runtime/asm_amd64.s:311 fp=0xc000062630 sp=0xc000062628 pc=0x454580
runtime.(*mheap).alloc(0x82fce0, 0x1, 0x7f0de8010029, 0x7f0de8592520)
        /tmp/go/src/runtime/mheap.go:930 +0x8a fp=0xc000062680 sp=0xc000062630 pc=0x42325a
runtime.(*mcentral).grow(0x830aa0, 0x0)
        /tmp/go/src/runtime/mcentral.go:256 +0x93 fp=0xc0000626c8 sp=0xc000062680 pc=0x416483
runtime.(*mcentral).cacheSpan(0x830aa0, 0x13c)
        /tmp/go/src/runtime/mcentral.go:106 +0x2ee fp=0xc000062728 sp=0xc0000626c8 pc=0x415f9e
runtime.(*mcache).refill(0x7f0deac06000, 0x29)
        /tmp/go/src/runtime/mcache.go:135 +0x86 fp=0xc000062748 sp=0xc000062728 pc=0x415a46
runtime.(*mcache).nextFree(0x7f0deac06000, 0x807029, 0x3, 0x3, 0x1)
        /tmp/go/src/runtime/malloc.go:786 +0x88 fp=0xc000062780 sp=0xc000062748 pc=0x40b048
runtime.mallocgc(0x160, 0x0, 0x0, 0x44420b)
        /tmp/go/src/runtime/malloc.go:939 +0x760 fp=0xc000062820 sp=0xc000062780 pc=0x40b950
runtime.growslice(0x61e1a0, 0xc007f71fb0, 0x24, 0x24, 0x15a, 0x3, 0xc000062930, 0x1d)
        /tmp/go/src/runtime/slice.go:175 +0x150 fp=0xc000062888 sp=0xc000062820 pc=0x440310
cmd/link/internal/objfile.(*objReader).patchDWARFName(0xc000062d68, 0xc007f55a30)
        /tmp/go/src/cmd/link/internal/objfile/objfile.go:361 +0x37e fp=0xc000062970 sp=0xc000062888 pc=0x52847e
cmd/link/internal/objfile.(*objReader).readSym(0xc000062d68)
        /tmp/go/src/cmd/link/internal/objfile/objfile.go:340 +0xff4 fp=0xc000062b50 sp=0xc000062970 pc=0x527454
cmd/link/internal/objfile.(*objReader).loadObjFile(0xc000062d68)
        /tmp/go/src/cmd/link/internal/objfile/objfile.go:128 +0x376 fp=0xc000062cc0 sp=0xc000062b50 pc=0x525cc6
cmd/link/internal/objfile.Load(0x81bd20, 0xc0000680f0, 0xc007f040f0, 0xc007616000, 0x3b993, 0xc007cd1590, 0x44)
        /tmp/go/src/cmd/link/internal/objfile/objfile.go:70 +0x1c4 fp=0xc000062e90 sp=0xc000062cc0 pc=0x525784
cmd/link/internal/ld.ldobj(0xc00068a000, 0xc007f040f0, 0xc007616000, 0x3ba22, 0xc007cd1590, 0x44, 0xc0006995a9, 0x3c, 0x0)
        /tmp/go/src/cmd/link/internal/ld/lib.go:1653 +0xc1f fp=0xc000063030 sp=0xc000062e90 pc=0x58595f
cmd/link/internal/ld.loadobjfile(0xc00068a000, 0xc007616000)
        /tmp/go/src/cmd/link/internal/ld/lib.go:883 +0x445 fp=0xc0000631c8 sp=0xc000063030 pc=0x57e935
cmd/link/internal/ld.(*Link).loadlib(0xc00068a000)
        /tmp/go/src/cmd/link/internal/ld/lib.go:381 +0x160 fp=0xc0000633a0 sp=0xc0000631c8 pc=0x57b350
cmd/link/internal/ld.Main(0x81bd20, 0x10, 0x20, 0x1, 0x7, 0x10, 0x67500e, 0x1b, 0x671bce, 0x14, ...)
        /tmp/go/src/cmd/link/internal/ld/main.go:207 +0xb3a fp=0xc000063510 sp=0xc0000633a0 pc=0x595dba
main.main()
        /tmp/go/src/cmd/link/main.go:65 +0x1cf fp=0xc000063f98 sp=0xc000063510 pc=0x5f88cf
runtime.main()
        /tmp/go/src/runtime/proc.go:200 +0x207 fp=0xc000063fe0 sp=0xc000063f98 pc=0x42c537
runtime.goexit()
        /tmp/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000063fe8 sp=0xc000063fe0 pc=0x4564d1
FAIL    github.com/mozilla/tls-observatory/worker/mozillaGradingWorker [build failed]
?       github.com/mozilla/tls-observatory/worker/ocspStatus    [no test files]
?       github.com/mozilla/tls-observatory/worker/sslLabsClientSupport  [no test files]
?       github.com/mozilla/tls-observatory/worker/symantecDistrust      [no test files]
?       github.com/mozilla/tls-observatory/worker/top1m [no test files]
Makefile:51: recipe for target 'test' failed
make: *** [test] Error 2`

**Comment by jammasterj89** [comment]
I was running make to create the app/tlsobs bin but that is now provided in /app so longer need to run make, closing issue.
